### ISSUE TITLE
Error when prepare S3DIS

### ISSUE THREAD

**Issue by linhaojia13** [aRI0U/RandLA-Net-pytorch#1]
It is a big surprise for me to find a Pytorch version of RandLA! Thank you for you good work! 

When I run the script 'prepare_s3dis.py' ,  it comes a ValueError:

Reencoding point clouds of area 1
Reencoding point clouds of area 2ding wall to point cloud...                      
Reencoding point clouds of area 3dding wall to point cloud...                    
Reencoding point clouds of area 4dding wall to point cloud...                     
Reencoding point clouds of area 5dding wall to point cloud...                     
Traceback (most recent call last):ding ceiling to point cloud...                  
  File "prepare_s3dis.py", line 45, in <module>
    points = np.loadtxt(elem, dtype=np.float32)
  File "/home/scsc01/.conda/envs/pytorch/lib/python3.6/site-packages/numpy/lib/npyio.py", line 1159, in loadtxt
    for x in read_data(_loadtxt_chunksize):
  File "/home/scsc01/.conda/envs/pytorch/lib/python3.6/site-packages/numpy/lib/npyio.py", line 1087, in read_data
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "/home/scsc01/.conda/envs/pytorch/lib/python3.6/site-packages/numpy/lib/npyio.py", line 1087, in <listcomp>
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "/home/scsc01/.conda/envs/pytorch/lib/python3.6/site-packages/numpy/lib/npyio.py", line 794, in floatconv
    return float(x)
ValueError: could not convert string to float: '103.0\x100000'

How can I solve this problem? By the way, it seems that you use the 
 Stanford3dDataset_v1.2 as the dataset, which is different with the original repo. Could you tell me why you make such choice?

**Comment by aRI0U** [comment]
Hi, we are glad that you are interested in our work and hope that it will be useful for you!
I guess that your issue comes from the dataset and not from the code itself, since it seems to work for you until some random point cloud, and that it works perfectly for me on the whole dataset (I ran the code 5 minutes ago). Do you use the aligned version of the dataset or the one we used?
Anyway what I suggest is to inspect the text file that cannot be encoded, and maybe to extract it from the archive again, or just delete it. Since prepare_s3dis.py does not convert files that have been converted earlier, you will not have to encode the whole dataset again so it should be quite fast to debug this.
Concerning the choice of dataset, there is no particular reason why we did not use aligned version. Actually we chose a version before original code of RandLA-Net were online, so that choice was quite arbitrary. However, if aligned version and not aligned one have the same structure, prepare_s3dis.py should work on both versions, so you should be able to use one or the other.
Finally, I have to warn you that our code is still on update and currently does not have results similar to the ones of the original repo. Therefore don't be surprised if the results you get with our code are not state-of-the-art at all !

**Comment by codename1995** [comment]
Tips for readers:

The incorrect number occurs in Line 323474 of the file S3DIS/Stanford3dDataset_v1.2/Area_5/office_19/Annotations/ceiling_1.txt
Correct the number 103.0�0000 to 103.000000.
