### ISSUE TITLE
performance on Semantic3D and S3DIS

### ISSUE THREAD

**Issue by ginobilinie** [aRI0U/RandLA-Net-pytorch#11]
Thanks for the implementation of randlanet in pytorch. I plan to use this copy of code to run some experiments on npm3d. Can you please share the performance you run on Semantic3D and S3DIS if it is convenient?

Thanks.

**Comment by Thibaud-Ardoin** [comment]
Hey ginobilinie, 

Thanks for your interest in our implementation !

Here are the results we got on S3DIS :
![Accuracy_npm3d](https://user-images.githubusercontent.com/36546850/88780945-018f0c00-d18c-11ea-9744-b16be42fd7a5.png)

This results are not as good as in the original paper. Probably because we didn't managed to balance the learning between the classes. Also, this git is a student project that we quickly stopped tried to improve, moving on new projects. 

You should be able to improve those results pretty easily, with some code fixing, training tricks and better hardware. We would happy to have new contributions to the git if it can help others !

And if you have more questions about our implementation please feel free to post new issues
