### ISSUE TITLE
pip installation doesn't include cuda version 

### ISSUE THREAD

**Issue by zeqinLi** [aRI0U/RandLA-Net-pytorch#7]
Hi,

I installed torch-points-kernels unsing the pip command:
pip install torch-points-kernels, but suprinsingly, it doesn't install the cuda version. In fact import torch_points_kernels.points_cuda produce an ModuleNotFoundError.

>ModuleNotFoundError: No module named 'torch_points_kernels.points_cuda'

How do i solve this problem

**Comment by aRI0U** [comment]
Hi,
I did not have such an error when I installed torch-point-kernels myself. Moreover, according to the authors of torch-point-kernels, pip installation should work. Since your issue seems to rely on that repository more than on RandLA-Net-pytorch, I would recommend you to take a look at torch-point-kernels issues and eventually creating a new one. Maybe you could try building from source or stuff like that, but I actually think that the best option is to ask the repo's authors themselves.
Here is the torch-point-kernels project page: https://github.com/nicolas-chaulet/torch-points-kernels

**Comment by chyohoo** [comment]
@zeqinLi Hi, I met the same problem, have you solved it?
